udp_ip = "0.0.0.0"
udp_port = 5005
tcp_ip = "0.0.0.0"
tcp_port = 5005
sensitivity = 40.0
screen_width = 2880
zoom_level = 2
angle_dead_zone = 0.05
interpolation_sleep = 0.005
accel_interpolation_steps = 3
accel_zero_g = 0.0
accel_filter_alpha = 0.35
accel_target_hysteresis_steps = 1
use_absolute_accel = false
accel_relative_sensitivity = 1.0
max_mouse_delta = 80
disable_accel_recenter = true
use_absolute_uinput = true
enable_hotkey_listener = true
